// PPM generator — standing boilerplate.
//
// RISK_FACTORS + the securities-law legend blocks are transcribed from the firm's
// final Risk Factors page set (Midtown & Midway 6.12.19, cross-checked against
// Chapel Hills East 1-21-24 — the text is deal-agnostic and identical across
// deals). A few evident typos in the source were corrected ("PROVIED"->"PROVIDED",
// "IR ANY"->"OR ANY", "EXPECATIONS"->"EXPECTATIONS"); wording otherwise verbatim.
// PROOFREAD against the master once before first external use.
//
// Dynamic-imported by the docx renderer so this text stays out of the main bundle.

import type { PpmDataSheet } from './template'
import { fmtMoney, fmtNum, fmtPct } from './template'

export const RISK_FACTORS_TITLE = 'RISK FACTORS'

export const RISK_FACTORS_INTRO =
  'This offering involves a significant degree of risk. The risks include, among others, the following:'

export const RISK_FACTORS: string[] = [
  'This offering is being made solely to "Accredited Investors" as that term is defined in Regulation D promulgated under the Securities Act of 1933, as amended, pursuant to an exemption which does not require the Wilkow Investor Company to furnish to potential investors the kind of information which would be furnished in connection with a registered offering of securities or an offering made pursuant to a different exemption, including a comprehensive description of the various risk and other factors which may be material to an investment of this nature. Accordingly, investors must rely on their own expertise or the advice of their own lawyers, accountants, investment advisors and other professionals in evaluating the merits and risks of this investment.',
  'There can be no assurances that the investment return objectives will be realized or that significant capital losses will not occur. Only investors able to lose the entirety of their investments should purchase units in the Wilkow Investor Company.',
  'Operating decisions rely to a large extent on the knowledge, judgment and experience of principals of the Manager. If any were to die or become disabled, or otherwise cease to be associated with Manager, such event may have an adverse effect on the business of the Operating Company and the Wilkow Investor Company.',
  'The ownership of real estate, which may have a redevelopment component, involves risks additional to those commonly associated with investment in operating real estate, such as those relating to: (A) competition from other properties for tenants; (B) inability to secure favorable financing or to satisfy conditions to financing commitments; (C) increased and/or unanticipated costs or delays of construction; (D) availability and timely receipt of zoning and other regulatory approvals; (E) delays in construction, or labor and material shortages; (F) adverse weather, strikes, and other unpredictable contingencies beyond the control of the Manager; (G) tenant lease defaults and tenant (and guarantor) insolvencies and bankruptcies; (H) the risk that a hazardous substance release may occur as a result of a leak, spill, emission or escape; and (I) the risk that in the event of a casualty, any proceeds received from insurance policies may not fully compensate the Property for the loss, as well as the risk that certain types of losses may only be insurable for amounts which are less than the Property’s replacement value.',
  'There are various tax risks associated with this Offering. No rulings have been sought from the Internal Revenue Service and the Memorandum does not purport to fully describe the tax consequences or risks of an investment in the Wilkow Investor Company. Each investor should consult with his own tax advisor with regard to such consequences.',
  'The Units are not readily transferable and should only be purchased for long-term investment. Units may be transferred only in compliance with the provisions of the Operating Agreement, which imposes limitations on transferability. There is no market for the Units and it is not anticipated that any market will develop for resale of the Units. As a result, a Member may be unable to sell or otherwise dispose of his interest in the Wilkow Investor Company and, therefore, must be prepared to bear the risk of an investment in the Units for an indefinite period of time.',
  'The investment in the Property is illiquid. As a result, there can be no assurance that the investment can be liquidated in a timely fashion. Disposition of investments may require a protracted period of time during which the strength of the economy or the interest rate environment may change affecting the value of the investment. No assurances can be given that additional capital will not be required in connection with the refinancing, operation and/or maintenance of the Property. Investors who elect not to participate in future capital calls, if any, risk having the Units purchased pursuant to this Memorandum, as well as Units previously purchased, being subordinated and diluted as a result of the preferences ascribed to any additional Units that may be issued from time to time.',
  'Investments in real estate are subject to various risks, including: adverse changes in general economic conditions, increasing interest rates, adverse local market conditions, the financial condition of tenants, buyers and sellers of properties, environmental laws and regulations, zoning laws and other governmental rules, environmental claims arising from unknown environmental problems, acts of G-d and other factors beyond the control of the Company and uninsurable losses. Rental rates for retail tenants are impacted by sales volume levels, and retail sales can be adversely impacted by a weak economy, weather conditions and the growing use of the internet, e-commerce and other online platforms. Poor sales can lead to tenant defaults or decisions by tenants to close their stores or elect not to renew leases or condition lease renewal proposals to a reduction in the size of their store. Government tenants, as well as tenants who are on a month-to-month lease, may terminate their lease on 30 days’ notice. Co-tenancy provisions, exclusive use and prohibited use restrictions and so-called "kick-out" provisions, if triggered, could allow a tenant to convert to a "percentage" rent lease or, in some cases, terminate its lease. Tenants may default or elect not to renew their leases. Such events may result in the existence of vacant space for a protracted period of time and unanticipated costs to release the vacated space.',
  'The investment in a single purpose entity acquiring one asset lacks diversification. The investment is leveraged with mortgage debt. Although the use of leverage may enhance returns, it may also risk the loss of equity capital. In the event that the cost of operating the Property exceeds estimates prepared in connection with the acquisition of the Property, the cash reserves and working capital may be depleted and lead to an additional capital call. If the Wilkow Investor Company is unable to fund its share of the capital call, its ownership interest in the Operating Company may be diluted.',
  'Conflicts of interest between the Manager, its affiliates and the Operating Company and/or the Wilkow Investor Company may arise under various circumstances. It is possible that an affiliate of the Manager may be terminated as property manager or removed from its position as Manager of the Operating Company, which could adversely affect the value of the Property and/or the Wilkow Investor Company’s investment.',
  'Affiliates of the Manager and certain other persons will receive certain compensation in connection with the management, operation and redevelopment of the Property, a portion of which will be payable without regard to the profitability of the Wilkow Investor Company and prior to any distributions to Members.',
  'The offering price of the Units has been determined by the Manager based on the cost of acquisition, as well as the projected net cost of owning and operating the Property which is expected to include the projected cost of improvements to the Property, leasing commissions and tenant improvement costs, as more fully described in this Memorandum. The offering price may not be an indication of the value of the Units or the value of the Property. No assurance is or can be given that the Units can be sold for the offering price or for any amount.',
  'The obligations of the principals of the Manager are not exclusive; the principals need only devote such amount of their time to the management of the affairs of the Operating Company and the Wilkow Investor Company as the principals determine is reasonably necessary. The principals expect to be engaged in other real estate activities and other unrelated business ventures for their own account or for the account of others during the term of the Wilkow Investor Company.',
  'No Member shall have the right, power or authority to participate in the ordinary and routine management of the affairs of the Operating Company or the Wilkow Investor Company or to exercise any control over the decisions of either Company. Major decisions at the Operating Company level will require the approval of all of the Members. The Manager shall have the exclusive right to manage, control and operate the affairs and business of the Wilkow Investor Company, to make all decisions in relation thereto, and shall have full, complete and exclusive discretion with respect to all such matters. Accordingly, no prospective investor should purchase any Units unless it is willing to entrust all aspects of management of the Wilkow Investor Company to the Manager, and all aspects of management of the Operating Company to the Wilkow Investor Company.',
  'Except for the historical information contained herein, any and all matters discussed in this Memorandum which constitute forward-looking statements (generally indicated by words such as "believes", "anticipates", "expects", "intends", and words of similar import) involve risks and uncertainties, including but not limited to economic, competitive, governmental and technological factors affecting the Operating Company’s and the Wilkow Investor Company’s operations, markets, products, services, prices and other factors discussed herein. Prospective investors should review this Memorandum and all other related documents, which upon request shall be made available for their inspection.',
  'A non-US individual or entity which becomes a subscriber in the Wilkow Investor Company will be subject to US income tax withholding with respect to dividends, if any, and certain interest income applicable to such subscriber. A non-US person or entity considering an investment in the Wilkow Investor Company should consult his/her or its own tax advisors with respect to the specific tax consequences to such person of such an investment under United States federal, state and local income tax laws, and with respect to the treatment of income and gain from such investment under the tax laws of any foreign jurisdiction in which such person is subject to tax.',
]

/** The ALL-CAPS securities legend blocks that follow the numbered risk factors. */
export const RISK_FACTORS_LEGENDS: string[] = [
  'THE SECURITIES OFFERED HEREBY HAVE NOT BEEN REGISTERED WITH, NOR APPROVED OR DISAPPROVED BY, THE UNITED STATES SECURITIES AND EXCHANGE COMMISSION, NOR BY THE SECURITIES REGULATORY AUTHORITY OF ANY STATE, NOR HAS ANY COMMISSION OR AUTHORITY PASSED UPON OR ENDORSED THE MERITS OF THIS OFFERING OR THE ACCURACY OR ADEQUACY OF THIS MEMORANDUM. ANY REPRESENTATION CONTRARY TO THE FOREGOING IS UNLAWFUL. THE UNITS MAY NOT BE TRANSFERRED IN THE ABSENCE OF ANY EFFECTIVE REGISTRATION STATEMENT OR AN OPINION OF COUNSEL THAT ANY EXEMPTION FROM REGISTRATION IS AVAILABLE.',
  'THIS MEMORANDUM DOES NOT CONSTITUTE AN OFFER OR SOLICITATION TO ANYONE IN ANY STATE OR IN ANY OTHER JURISDICTION IN WHICH SUCH AN OFFER OR SOLICITATION IS NOT AUTHORIZED.',
  'THE WILKOW INVESTOR COMPANY IS NOT REGISTERED AND DOES NOT INTEND TO REGISTER AS AN INVESTMENT COMPANY UNDER THE INVESTMENT COMPANY ACT. NEITHER THE MANAGER NOR ANY OF ITS AFFILIATES ARE REGISTERED OR REPORTING AS AN INVESTMENT ADVISER UNDER THE INVESTMENT ADVISERS ACT OR ANY SIMILAR STATE LAWS. CONSEQUENTLY, INVESTORS WILL NOT HAVE CERTAIN REGULATORY PROTECTIONS PROVIDED TO INVESTORS IN REGISTERED INVESTMENT COMPANIES OR BE ENTITLED TO THE PROTECTIONS AFFORDED TO INVESTMENTS THAT ARE ADVISED BY REGISTERED INVESTMENT ADVISERS.',
  'REFERENCE SHOULD BE MADE TO THE LIMITED LIABILITY COMPANY OPERATING AGREEMENTS OF THE OPERATING COMPANY AND THE WILKOW INVESTOR COMPANY FOR THE COMPLETE INFORMATION CONCERNING THE RIGHTS AND OBLIGATIONS OF THE PARTIES TO THOSE AGREEMENTS, COPIES OF WHICH ARE AVAILABLE FOR REVIEW UPON REQUEST. CERTAIN PROVISIONS OF THOSE OPERATING AGREEMENTS MAY BE SUMMARIZED IN THIS MEMORANDUM, BUT IT SHOULD NOT BE ASSUMED THAT THE SUMMARIES ARE COMPLETE.',
  'THIS MEMORANDUM IS SUBMITTED IN CONNECTION WITH THE PRIVATE PLACEMENT OF THESE LIMITED LIABILITY COMPANY INTERESTS ("UNITS") AND MAY NOT BE REPRODUCED OR USED FOR ANY OTHER PURPOSE. ANY ACTION CONTRARY TO THESE RESTRICTIONS MAY INVOLVE A VIOLATION OF CERTAIN STATES’ BLUE SKY LAWS.',
  'THE MANAGER HAS AGREED TO MAKE AVAILABLE, PRIOR TO THE CONSUMMATION OF THE TRANSACTIONS CONTEMPLATED HEREIN, TO EACH OFFEREE OF UNITS OR HIS REPRESENTATIVE(S) OR BOTH, THE OPPORTUNITY TO ASK QUESTIONS OF, AND RECEIVE ANSWERS FROM THE MANAGER CONCERNING THE TERMS AND CONDITIONS OF THIS OFFERING, AND TO OBTAIN ANY ADDITIONAL INFORMATION, TO THE EXTENT THEY POSSESS SUCH INFORMATION OR CAN ACQUIRE IT WITHOUT UNREASONABLE EFFORT OR EXPENSE, NECESSARY TO VERIFY THE ACCURACY OF THE INFORMATION SET FORTH HEREIN. REQUESTS FOR FURTHER INFORMATION SHOULD BE MADE TO THE MANAGER AND SUCH INFORMATION SHOULD ONLY BE RELIED UPON WHEN FURNISHED IN WRITTEN FORM AND SIGNED BY THE MANAGER. NO SELLING AGENT, BROKER, SALESMAN, OR ANY OTHER PERSON HAS BEEN AUTHORIZED TO GIVE ANY INFORMATION OR TO MAKE ANY REPRESENTATIONS, OTHER THAN THOSE CONTAINED IN THE MEMORANDUM AND IF GIVEN OR MADE, SUCH INFORMATION OR REPRESENTATIONS MUST NOT BE RELIED UPON AS HAVING BEEN AUTHORIZED BY THE MANAGER.',
  'THE FINANCIAL ANALYSES ARE BASED, IN PART, ON ASSUMPTIONS CONCERNING FACTS AND EVENTS OVER WHICH THE WILKOW INVESTOR COMPANY AND THE MANAGER HAVE NO CONTROL, AND WHICH COULD, IF THEY CHANGE, PRODUCE RESULTS SIGNIFICANTLY DIFFERENT FROM THOSE SET FORTH IN THE FINANCIAL FORECASTS. PROSPECTIVE INVESTORS SHOULD NOT MAKE THEIR INVESTMENT DECISIONS TO PURCHASE UNITS SOLELY ON THE BASIS OF THE FORECASTS CONTAINED HEREIN, AS THEY DO NOT CONSTITUTE A GUARANTY AS TO THE RESULTS OF THE OPERATIONS. PROSPECTIVE INVESTORS ARE CAUTIONED AGAINST UNDUE RELIANCE ON THESE FORECASTS AND, IN ANY EVENT, SHOULD CAREFULLY REVIEW THE UNDERLYING ASSUMPTIONS NOTED THEREIN.',
  'THIS DOCUMENT CONTAINS FORWARD-LOOKING STATEMENTS RELATING TO SUCH MATTERS AS ANTICIPATED FINANCIAL PERFORMANCE, BUSINESS PROSPECTS, SERVICES, DEVELOPMENTAL ACTIVITIES, AMOUNT OF FUNDS MADE AVAILABLE TO THE WILKOW INVESTOR COMPANY FROM THIS OFFERING AND OTHER SOURCES, AND SIMILAR MATTERS. THE PRIVATE SECURITIES LITIGATION REFORM ACT OF 1995 PROVIDES A SAFE HARBOR FOR FORWARD-LOOKING STATEMENTS. IN ORDER TO CONFORM WITH THE TERMS OF THE SAFE HARBOR, THE COMPANY CAUTIONS THAT THE FOREGOING CONSIDERATIONS AS WELL AS A VARIETY OF OTHER FACTORS NOT SET FORTH HEREIN COULD CAUSE THE OPERATING COMPANY’S, AND THE WILKOW INVESTOR COMPANY’S, ACTUAL RESULTS AND EXPERIENCE TO DIFFER WIDELY OR MATERIALLY FROM THE ANTICIPATED RESULTS OR OTHER EXPECTATIONS IN THE COMPANY’S FORWARD-LOOKING STATEMENTS.',
  'THIS MEMORANDUM INCLUDES "FORWARD-LOOKING STATEMENTS" WHICH REPRESENT OUR EXPECTATIONS OR BELIEFS CONCERNING FUTURE EVENTS THAT INVOLVE RISKS AND UNCERTAINTIES, INCLUDING THOSE ASSOCIATED WITH OUR ABILITY TO OBTAIN FINANCING FOR OUR CURRENT AND FUTURE OPERATIONS. ALL STATEMENTS OTHER THAN THOSE STATEMENTS OF HISTORICAL FACTS INCLUDED IN THE MEMORANDUM ARE FORWARD-LOOKING STATEMENTS. ALTHOUGH WE BELIEVE THAT THE EXPECTATIONS REFLECTED IN SUCH FORWARD-LOOKING STATEMENTS ARE REASONABLE, WE CANNOT ASSURE YOU THAT SUCH EXPECTATIONS WILL PROVE TO BE CORRECT. IMPORTANT FACTORS THAT COULD CAUSE ACTUAL RESULTS TO DIFFER MATERIALLY FROM OUR EXPECTATIONS ARE DISCLOSED IN THE MEMORANDUM. ALL SUBSEQUENT WRITTEN AND ORAL FORWARD-LOOKING STATEMENTS ATTRIBUTABLE TO US OR PERSONS ACTING ON BEHALF OF THE INVESTOR COMPANY ARE EXPRESSLY QUALIFIED BY THESE CAUTIONARY STATEMENTS.',
  'PROSPECTIVE INVESTORS SHOULD NOT CONSTRUE THE CONTENTS OF THIS MEMORANDUM, OR ANY PRIOR OR SUBSEQUENT COMMUNICATIONS FROM THE WILKOW INVESTOR COMPANY OR ANY OF ITS AGENTS, OFFICERS OR REPRESENTATIVES, AS LEGAL OR TAX ADVICE; EACH OFFEREE SHOULD CONSULT HIS OWN ADVISORS AS TO LEGAL, TAX, AND RELATED MATTERS CONCERNING AN INVESTMENT IN THE WILKOW INVESTOR COMPANY.',
  'THIS CONFIDENTIAL OFFERING MEMORANDUM DOES NOT SET FORTH COMPLETE INFORMATION RELATING TO THE TAX EFFECTS OF AN INVESTMENT IN THE WILKOW INVESTOR COMPANY. EACH PROSPECTIVE INVESTOR SHOULD CONSULT WITH ITS OWN COUNSEL, ACCOUNTANTS OR OTHER ADVISORS AS TO THE US FEDERAL (AS WELL AS STATE AND LOCAL) TAX CONSEQUENCES OF ITS INVESTMENT IN THE COMPANY, WHICH MAY DIFFER SUBSTANTIALLY FOR DIFFERENT TYPES OF TAXPAYERS (INDIVIDUALS, CORPORATIONS, ETC.). IN PARTICULAR, INVESTMENT IN THE WILKOW INVESTOR COMPANY BY ENTITIES SUBJECT TO ERISA AND BY OTHER TAX-EXEMPT ENTITIES REQUIRES SPECIAL CONSIDERATION. TRUSTEES OR ADMINISTRATORS OF SUCH ENTITIES ARE URGED TO CAREFULLY REVIEW THE MATTERS DISCUSSED IN THIS MEMORANDUM.',
]

// ---------------------------------------------------------------------------
// Offering Page (the personalized one-pager at the front of the package)
// ---------------------------------------------------------------------------

export interface OfferingPageContent {
  headline: string
  dateLine: string
  reLines: string[]
  paragraphs: string[]
  accreditedLegend: string
  offereeLine: string
}

export function buildOfferingPage(ds: PpmDataSheet): OfferingPageContent {
  const raise = ds.investorCompanyTotal
  const unitPrice = ds.classAUnitPrice
  return {
    headline: 'CONFIDENTIAL PRIVATE PLACEMENT MEMORANDUM',
    dateLine: ds.ppmDate || '____',
    reLines: [
      `Re:\t${ds.investorCompanyName || '____'}`,
      `\t${ds.propertyName || '____'}`,
      `\t${[ds.city, ds.state].filter(Boolean).join(', ') || '____'}`,
    ],
    paragraphs: [
      `${fmtMoney(raise)} of Limited Liability Company Class A Units (${fmtMoney(unitPrice)} per Unit)`,
      `Minimum Subscription: ${fmtNum(ds.minSubscriptionUnits)} Class A Units`,
      `${ds.investorCompanyName || '____'}, a newly formed Delaware limited liability company (the "Wilkow Investor Company") intends to acquire a ${fmtPct(ds.mjwPct, 0)} ownership interest in ${ds.jvVehicleName || '____'}, a new Delaware limited liability company (the "Operating Company"), which will be formed to be the owner of a 100% fee simple interest in the property commonly known as ${ds.propertyName || '____'} (the "Property").`,
      `The Property covers ${fmtNum(ds.glaSf)} square feet and is currently ${fmtPct(ds.occupancyPct, 0)} leased. It is located in ${[ds.city, ds.state].filter(Boolean).join(', ') || '____'}.`,
      ds.jvPartnerBlurb
        ? `The ${fmtPct(ds.jvPartnerPct, 0)} owner of the Operating Company will be an entity owned by an affiliate of ${ds.jvPartnerName || '____'}. ${ds.jvPartnerBlurb}`
        : `The ${fmtPct(ds.jvPartnerPct, 0)} owner of the Operating Company will be an entity owned by an affiliate of ${ds.jvPartnerName || '____'}.`,
      `The Acquisition Budget (including the purchase price of ${fmtMoney(ds.purchasePrice)}) for the Property is ${fmtMoney(ds.totalCapitalization)}, which shall be funded by: (a) a new non-recourse mortgage loan (the "Mortgage Loan") in the initial principal amount of approximately ${fmtMoney(ds.loanAmount)}; and (b) equity capital in the amount of ${fmtMoney(ds.totalEquity)} - ${fmtPct(ds.mjwPct, 0)} of which, or ${fmtMoney(ds.mjwEquity)}, will be funded by the Wilkow Investor Company. The non-member manager of the Wilkow Investor Company will be ${ds.managerIncName || '____'}, a newly organized Delaware corporation, the stockholders of which are ${ds.managerStockholders}.`,
      `The Wilkow Investor Company is offering up to ${fmtNum(ds.classAUnits)} Class A Units to selected accredited investors at the rate of ${fmtMoney(unitPrice)} per Class A Unit for the purpose of raising ${fmtMoney(raise)} of equity capital to fund: (i) the Wilkow Investor Company's share of the equity capital requirement in the amount of ${fmtMoney(ds.mjwEquity)}; and (ii) amounts to cover the Wilkow Investor Company's expenses, a working capital/contingency reserve and a sponsor fee of not more than ${fmtMoney(ds.sponsorFee)}, which shall be payable to M & J Wilkow.`,
      `The capital contribution for the Class A Units will be funded in one lump sum payable on or before ${ds.subscriptionDeadline || '____'}.`,
    ],
    accreditedLegend:
      'THIS OFFERING IS BEING MADE SOLELY TO "ACCREDITED INVESTORS" AS DEFINED IN PARAGRAPH 2(b) OF THE ATTACHED SUBSCRIPTION AGREEMENT.',
    offereeLine: 'Name of Offeree: ________________________',
  }
}
