-- 20240178  Correct the management fee shown 100x too high on 29 abstracts.
--
-- Found by walking the UI signed-in on 2026-08-01: Target's abstract read "management
-- fee 175.00% per PMA line" in the REA/property-management panel. Gateway's fee is 1.75%.
--
-- PRODUCER ALREADY FIXED (commit f96dfd3, lease-abstract v32): that function multiplied
-- management_agreements.mgmt_fee_pct by 100, but the column stores a PERCENT NUMBER
-- (Gateway 1.75 = 1.75%, KM 3.1, Magnolia 3.0 / 2.75) - the exception to CLAUDE.md's
-- "percentages are decimals" convention, as the column name's _pct implies. That was the
-- only x100 on mgmt_fee_pct in the repo; both UI consumers render it raw. This migration
-- repairs the strings the old code already persisted, which live in the stored abstract
-- JSON at rea_pma.pma_manager and therefore also reach exported PDFs.
--
-- COMPLETE SET OF BAD TOKENS, enumerated before writing rather than assumed - every
-- percent token >= 100% across all 100 abstracts, since no management fee is >= 100%:
--     175.00%  x18 abstracts  -> 1.75%   (Gateway)
--     310.00%  x8             -> 3.10%   (KM East + KM West)
--     300.00%  x3             -> 3.00%   (Magnolia)
--     275.00%  x2             -> 2.75%   (Magnolia)
-- 31 token occurrences across 29 abstracts - Magnolia carries several current PMA rows,
-- so its pmaLine can hold more than one fee. Each corrected value equals the actual
-- mgmt_fee_pct in management_agreements, which is the independent check that the
-- divide-by-100 reading is right.
--
-- Written as `rea_pma.pma_manager` DOT-PATH overrides, not a whole-object rea_pma
-- override, so subject_to_rea / rea_name / tenant_impact / notes are untouched. Verified
-- first that no abstract already carries a 'rea_pma' or 'rea_pma.pma_manager' override,
-- so nothing is being clobbered and the || merge only adds a key.
--
-- These overrides SURVIVE regeneration, but once an abstract is regenerated by v32 the
-- underlying value will be correct anyway and the override becomes a harmless no-op.

update lease_abstracts la
set overrides = coalesce(la.overrides::jsonb, '{}'::jsonb) || jsonb_build_object(
      'rea_pma.pma_manager',
      regexp_replace(
        regexp_replace(
          regexp_replace(
            regexp_replace(la.abstract->'rea_pma'->>'pma_manager',
              '175\.00%', '1.75%', 'g'),
            '310\.00%', '3.10%', 'g'),
          '300\.00%', '3.00%', 'g'),
        '275\.00%', '2.75%', 'g')
    )
where la.abstract->'rea_pma'->>'pma_manager' ~ '[0-9]{3,}\.[0-9]{2}%';

-- VERIFIED after applying, against a prediction made before writing:
--   overrides written        = 29
--   effective strings still carrying a >=100% token = 0
--   now showing 1.75% = 18 ; 3.10% = 11 (8 fixed + 3 already correct) ; Magnolia = 3
